### ISSUE TITLE
Spring retry + spring boot 1.5.x + java 10 issue 

### ISSUE THREAD

**Issue by tdanylchuk** [spring-projects/spring-retry#118]
Hello, trying to run SB app with `@EnabledRetry` with java 10, but unfortunately during startup app is failing to load application context.
Here is stack trace for this :
```
[07/02/2018 14:18:35:711 UTC] ERROR SpringApplication: Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.context.event.internalEventListenerProcessor': Initialization of bean failed; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.8.RELEASE.jar!/:1.5.8.RELEASE]
	at org.springframework.boot.SpringApplication$run.call(Unknown Source) [spring-boot-1.5.8.RELEASE.jar!/:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-all-2.4.12.jar!/:2.4.12]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-all-2.4.12.jar!/:2.4.12]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-all-2.4.12.jar!/:2.4.12]
	at com.playtika.deployment.DeploymentPackageApplication.main(DeploymentPackageApplication.groovy:55) [classes!/:1.0.27-SNAPSHOT]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [deployment-package-1.0.27-SNAPSHOT.jar:1.0.27-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [deployment-package-1.0.27-SNAPSHOT.jar:1.0.27-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [deployment-package-1.0.27-SNAPSHOT.jar:1.0.27-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [deployment-package-1.0.27-SNAPSHOT.jar:1.0.27-SNAPSHOT]
Caused by: java.lang.NullPointerException
	at org.springframework.retry.annotation.RetryConfiguration.getClassFilter(RetryConfiguration.java:109) ~[spring-retry-1.2.1.RELEASE.jar!/:?]
	at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:275) ~[spring-aop-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.aop.support.AopUtils.canApply(AopUtils.java:260) ~[spring-aop-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.aop.support.AopUtils.findAdvisorsThatCanApply(AopUtils.java:301) ~[spring-aop-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findAdvisorsThatCanApply(AbstractAdvisorAutoProxyCreator.java:119) ~[spring-aop-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:89) ~[spring-aop-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:70) ~[spring-aop-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:346) ~[spring-aop-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:298) ~[spring-aop-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1633) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
	... 24 more

```
Spring boot: 1.5.8
Spring retry: 1.2.1

Disabling `//@EnableRetry` and everything works as expected.

pom.xml :
```
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.8.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.retry</groupId>
			<artifactId>spring-retry</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aspects</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aop</artifactId>
		</dependency>
	</dependencies>
```
DemoApplication.java :
```
@EnableRetry
@SpringBootApplication
public class DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}
}
```

**Comment by tdanylchuk** [comment]
After small investigation I found the root case:
Init method not being invoked in Boot 1.5.x + java 10 since `CommonAnnotationBeanPostProcessor` isn't being initialized because of this check:
```
private static final boolean jsr250Present =
			ClassUtils.isPresent("javax.annotation.Resource", AnnotationConfigUtils.class.getClassLoader());
```
As for boot 2.0 it works correctly despite of same code check, seems like issue related to class loader...

A lot of features are being initialized by `CommonAnnotationBeanPostProcessor` like `PostConstruct`, `PreDestroy` etc., I assume they won't work with java 10 and boot 1.5.x.

@philwebb sorry for tagging you here, but I can't file issue on spring framework, but question is - is this known issue and is there any change to resolve this for java 10?

**Comment by philwebb** [comment]
> sorry for tagging you here, but I can't file issue on spring framework, question is - is this known issue and is there any change to resolve this for java 10?

I'm not aware of anything specific in the Spring Boot codebase. Perhaps something specific was done in Spring Framework. I'm not sure if Spring Framework 4.3.x even officially supports Java 10. We certainly don't have any tests in Spring Boot 1.5.x to ensure compatibility. Is there any specific reason that you can't upgrade?

> I can't file issue on spring framework

Since last week you should be able to log into https://jira.spring.io/browse/SPR using your GitHub creds if that helps.

**Comment by tdanylchuk** [comment]
As I understand you are advising to upgrade my project to boot 2.0, if yes - for this particular project I can do this, but this only one project that I currently work on.
In future I willing to migrate all other projects (dozens) to java 10, since it has great support of containers,
but unfortunately it will take too much time to migrate all of them, so I'm searching some easy ways to do so.

> Since last week you should be able to log into https://jira.spring.io/browse/SPR using your GitHub creds if that helps.

I've actually, logged in, but unfortunately it says to me:
> Sorry, you can't create any issues right now, as you need to have access to a JIRA application to be able to create issues. To gain application access you need to be a member of a group assigned to an application.

**Comment by philwebb** [comment]
@tdanylchuk I've raised the JIRA issue with our ops team. You might be able to create an account directly rather than using a GitHub login in the meantime.

**Comment by trevormarshall** [comment]
@tdanylchuk I've fixed your JIRA account and am working on the issue with the plugin now.

**Comment by tdanylchuk** [comment]
Thank you, works for me now, filed issue under https://jira.spring.io/browse/SPR-17011
