### ISSUE TITLE
Multiple recovery methods in same class results in ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pacbeckh** [spring-projects/spring-retry#145]
Given the following example

```
package foo.bar;

import org.springframework.retry.annotation.Recover;
import org.springframework.retry.annotation.Retryable;
import org.springframework.stereotype.Component;

import java.util.Optional;
import java.util.UUID;

@Component
public class MinimumExample {

    @Retryable(
        maxAttempts = 1,
        include = {CustomException.class}
    )
    public Optional<Foo> getFoo(UUID fooId) {
        throw new CustomException();
    }

    @Retryable(
        maxAttempts = 1,
        include = {CustomException.class}
    )
    public Optional<Bar> getBar(UUID barId) {
        throw new CustomException();
    }

    @Recover
    public Optional<Foo> reoverForFoo(CustomException e, UUID barId) {
        return Optional.empty();
    }

    @Recover
    public Optional<Bar> recoverForBar(CustomException e, UUID fooId) {
        return Optional.empty();
    }

    public static class CustomException extends RuntimeException {
    }

    public static class Foo {
    }

    public static class Bar {
    }

}

```

I get the following exception:

```
java.lang.ArrayIndexOutOfBoundsException: -1

	at org.springframework.retry.annotation.RecoverAnnotationRecoveryHandler.compareParameters(RecoverAnnotationRecoveryHandler.java:124)
	at org.springframework.retry.annotation.RecoverAnnotationRecoveryHandler.findClosestMatch(RecoverAnnotationRecoveryHandler.java:95)
	at org.springframework.retry.annotation.RecoverAnnotationRecoveryHandler.recover(RecoverAnnotationRecoveryHandler.java:59)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$ItemRecovererCallback.recover(RetryOperationsInterceptor.java:141)
	at org.springframework.retry.support.RetryTemplate.handleRetryExhausted(RetryTemplate.java:512)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:351)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:115)
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:153)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
```

I believe it is related to the fix for #85  in PR  #125 ,
the line `if (parameterTypes.length > 0 && parameterTypes[0] == Throwable.class) {` and the corresponding tests assumes only uses Throwable as a parameter type, even though customException types are allowed.

Besides this, the other issue is that both recover methods have the same parameters. If this is to be supported, we might need to consider the return types as well. 
Or specify the recovery method in the retryable annotation.

**Comment by dsyer** [comment]
The “==“ probably should have been assignableFrom I guess. That’s an easy change? Why not send a PR? Adding the return type would be useful too, and also doable. Maybe a separate PR for that? Not sure I’m interested in the other idea.

**Comment by kevonoff** [comment]
This is my first contribution so if there is anything that needs to be fixed feel free to let me know.

**Comment by slilie** [comment]
Thanks for fixing this! Is there a repository where snapshots are published? Or will 1.2.5 be released soon?

**Comment by artembilan** [comment]
This one is there for you:
```
<repository>
					<id>spring-snapshots</id>
					<name>Spring Snapshots</name>
					<url>https://repo.spring.io/libs-snapshot-local</url>
					<snapshots>
						<enabled>true</enabled>
					</snapshots>
</repository>
```

We don't have plans for releasing that one. May be for the next Spring Boot 1.5.22: https://github.com/spring-projects/spring-boot/milestone/143 ...

**Comment by manhcuongbk56** [comment]
Btw. This code still has problem. If the first arg is not assignable from `Throwable` => `startingIndex` stays `0` then it will throws `index out of bound`.
```java
private boolean compareParameters(Object[] args, int argCount, Class<?>[] parameterTypes) {
		if (argCount == (args.length + 1)) {
			int startingIndex = 0;
			if (parameterTypes.length > 0 && parameterTypes[0] == Throwable.class) {
				startingIndex = 1;
			}
			for (int i = startingIndex; i < parameterTypes.length; i++) {
				final Object argument = args[i-1];
				if (argument == null) {
					continue;
				}
				if (parameterTypes[i] != argument.getClass()) {
					return false;
				}
			}
			return true;
		}
		return false;
	}

**Comment by artembilan** [comment]
@manhcuongbk56 ,

thank you for feedback, however I think we have a fix in the current `master`. This is an actual code you are pointing:
```
private boolean compareParameters(Object[] args, int argCount, Class<?>[] parameterTypes) {
		if (argCount == (args.length + 1)) {
			int startingIndex = 0;
			if (parameterTypes.length > 0 && Throwable.class.isAssignableFrom(parameterTypes[0])) {
				startingIndex = 1;
			}
			for (int i = startingIndex; i < parameterTypes.length; i++) {
				final Object argument = i - startingIndex < args.length ? args[i - startingIndex] : null;
				if (argument == null) {
					continue;
				}
				if (!parameterTypes[i].isAssignableFrom(argument.getClass())) {
					return false;
				}
			}
			return true;
		}
		return false;
}
```
So, we never have `0 -1`. Would you mind to check with the latest `1.2.5.BUILD-SNAPSHOT` ?

**Comment by manhcuongbk56** [comment]
@artembilan 
Thank you, :D. It fix my problem, 👍
