### ISSUE TITLE
Multiple recovery methods in same class results in ArrayIndexOutOfBoundsException #2

### ISSUE THREAD

**Issue by pictin** [spring-projects/spring-retry#185]
Given the following example
```
package com.example.demo;

import org.springframework.retry.annotation.Recover;
import org.springframework.retry.annotation.Retryable;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Component
public class MinimumExample {

    @Retryable(
            maxAttempts = 1,
            include = {CustomException.class}
    )
    public Optional<Foo> getFoo(List<UUID> fooIds) {
        throw new CustomException();
    }

    @Recover
    public Optional<Foo> recoverForFoo(CustomException e, List<UUID> fooIds) {
        return Optional.empty();
    }

    @Recover
    public Optional<Foo> recoverForFoo(CustomException e, List<UUID> fooIds, UUID barId) {
        return Optional.empty();
    }

    public static class CustomException extends RuntimeException {
    }

    public static class Foo {
    }
}
```
I get the following exception:
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at org.springframework.retry.annotation.RecoverAnnotationRecoveryHandler.compareParameters(RecoverAnnotationRecoveryHandler.java:124) ~[spring-retry-1.2.4.RELEASE.jar:na]
	at org.springframework.retry.annotation.RecoverAnnotationRecoveryHandler.findClosestMatch(RecoverAnnotationRecoveryHandler.java:95) ~[spring-retry-1.2.4.RELEASE.jar:na]
	at org.springframework.retry.annotation.RecoverAnnotationRecoveryHandler.recover(RecoverAnnotationRecoveryHandler.java:59) ~[spring-retry-1.2.4.RELEASE.jar:na]
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$ItemRecovererCallback.recover(RetryOperationsInterceptor.java:141) ~[spring-retry-1.2.4.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.handleRetryExhausted(RetryTemplate.java:512) ~[spring-retry-1.2.4.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:351) ~[spring-retry-1.2.4.RELEASE.jar:na]
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:180) ~[spring-retry-1.2.4.RELEASE.jar:na]
```

This is similar to [#145](https://github.com/spring-projects/spring-retry/issues/145), but the root cause is a little different. In this case, the method `compareParameters()` tries to match parameters, but fails to account for subclasses of those parameters. Specifically, the recovery method had specified a "List" type parameter, while the actual runtime parameter is a concrete class (like "ArrayList"). `compareParameters()` considers this a mismatch, because it performs a rigid check `if (parameterTypes[i] != argument.getClass())`

As a minimum, rigid check should be replaced with "isAssignableFrom()", similar to "Throwable" treatment. This should fix the exception.

However, minimal fix might make parameter type comparison a little too lax. Ideally, we need to implement "calculateDistance()" for parameter types as well.

**Comment by artembilan** [comment]
Sounds like a bug and looks like you are fully on board with the problem.
Would you mind to contribute the fix?
We can start with a simpler one and then come up with a robust one eventually.

Thank you for heads up!

**Comment by pictin** [comment]
Actually, this is a duplicate of https://github.com/spring-projects/spring-retry/issues/174
The #174 is fixed, but the fix is not released yet.
