### ISSUE TITLE
Retry interceptor bean doesn't override default max attempts

### ISSUE THREAD

**Issue by andrewe123** [spring-projects/spring-retry#35]
@Bean
         public RetryOperationsInterceptor myInterceptor() {
            return RetryInterceptorBuilder.stateless().maxAttempts(4).backOffOptions(1000, 1.1,      5000).build();
         }
    ...
        @Retryable(interceptor="myInterceptor")
        get(String id);

The backOffOptions work as specified in the bean, but the max attempts is always 3.

**Comment by garyrussell** [comment]
I just tested with your exact configuration and it worked as expected for me...

    11:31:34.206 DEBUG [SimpleAsyncTaskExecutor-1][org.springframework.retry.support.RetryTemplate] Retry: count=0
    Received1: Hello World 1 attempt 1
    11:31:34.209 DEBUG [SimpleAsyncTaskExecutor-1][org.springframework.retry.backoff.ExponentialBackOffPolicy] Sleeping for 1000
    11:31:35.215 DEBUG [SimpleAsyncTaskExecutor-1][org.springframework.retry.support.RetryTemplate] Checking for rethrow: count=1
    11:31:35.215 DEBUG [SimpleAsyncTaskExecutor-1][org.springframework.retry.support.RetryTemplate] Retry: count=1
    Received1: Hello World 1 attempt 2
    11:31:35.215 DEBUG [SimpleAsyncTaskExecutor-1][org.springframework.retry.backoff.ExponentialBackOffPolicy] Sleeping for 1100
    11:31:36.320 DEBUG [SimpleAsyncTaskExecutor-1][org.springframework.retry.support.RetryTemplate] Checking for rethrow: count=2
    11:31:36.320 DEBUG [SimpleAsyncTaskExecutor-1][org.springframework.retry.support.RetryTemplate] Retry: count=2
    Received1: Hello World 1 attempt 3
    11:31:36.320 DEBUG [SimpleAsyncTaskExecutor-1][org.springframework.retry.backoff.ExponentialBackOffPolicy] Sleeping for 1210
    11:31:37.535 DEBUG [SimpleAsyncTaskExecutor-1][org.springframework.retry.support.RetryTemplate] Checking for rethrow: count=3
    11:31:37.536 DEBUG [SimpleAsyncTaskExecutor-1][org.springframework.retry.support.RetryTemplate] Retry: count=3
    Received1: Hello World 1 attempt 4
    11:31:37.536 DEBUG [SimpleAsyncTaskExecutor-1][org.springframework.retry.support.RetryTemplate] Checking for rethrow: count=4
    11:31:37.536 DEBUG [SimpleAsyncTaskExecutor-1][org.springframework.retry.support.RetryTemplate] Retry failed last attempt: count=4
    11:31:37.537 WARN  [SimpleAsyncTaskExecutor-1][org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler] Execution of Rabbit message listener failed.
    org.springframework.amqp.rabbit.listener.exception.ListenerExecutionFailedException: Listener method 'public void foo.Consumer.handleHello1(java.lang.String)' threw exception
    	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:125)
    	at org.springframework.amqp.rabbit.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:92)
    	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:757)
    	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:680)
    	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$001(SimpleMessageListenerContainer.java:93)
    	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$1.invokeListener(SimpleMessageListenerContainer.java:183)
    	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.invokeListener(SimpleMessageListenerContainer.java:1352)
    	at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.executeListener(AbstractMessageListenerContainer.java:661)
    	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doReceiveAndExecute(SimpleMessageListenerContainer.java:1096)
    	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.receiveAndExecute(SimpleMessageListenerContainer.java:1080)
    	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.access$800(SimpleMessageListenerContainer.java:93)
    	at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1197)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.RuntimeException: foo

Are you confusing `maxAttempts` with `maxRetries` ?

Perhaps you have another bean with the same name that overrides this one?

**Comment by andrewe123** [comment]
Thanks for verifying. It looks like the issue was in my test.
