### ISSUE TITLE
MetricsRetryListener#close() throws "No 'Timer.Sample' registered" exception

### ISSUE THREAD

**Issue by basovnik** [spring-projects/spring-retry#469]
The operation [MetricsRetryListener#close()](https://github.com/spring-projects/spring-retry/blob/42158baa44a32a4d2fe99c17cdaec6e1a89c4ee6/src/main/java/org/springframework/retry/support/MetricsRetryListener.java#L116) from time to time throws the following error:
```
j.l.IllegalStateException: No 'Timer.Sample' registered for '[RetryContext: count=0, lastException=null, exhausted=false]'. Was the 'open()' called?
	at o.s.util.Assert.state(Assert.java:97)
	at o.s.r.s.MetricsRetryListener.close(MetricsRetryListener.java:113)
	at o.s.r.s.RetryTemplate.doCloseInterceptors(RetryTemplate.java:619)
	at o.s.r.s.RetryTemplate.doExecute(RetryTemplate.java:413)
	at o.s.r.s.RetryTemplate.execute(RetryTemplate.java:233)
	at o.s.r.i.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:113)
	at o.s.r.a.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:162)
	at o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at o.s.a.f.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at c.w.t.c.a.VpnRouteStatusController$$SpringCGLIB$$0.create(<generated>)
	at j.i.r.GeneratedMethodAccessor179.invoke(Unknown Source)
	at j.i.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at j.l.reflect.Method.invoke(Method.java:569)
	at o.s.w.m.s.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at o.s.w.m.s.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at o.s.w.s.m.m.a.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
	at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
	at o.s.w.s.m.m.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at o.s.w.s.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at o.s.w.s.DispatcherServlet.doService(DispatcherServlet.java:979)
	at o.s.w.s.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at o.s.w.s.FrameworkServlet.doPost(FrameworkServlet.java:914)
	at j.s.http.HttpServlet.service(HttpServle...
	```

**Comment by artembilan** [comment]
@basovnik ,

Let's double check first!
Can you confirm, please, that the mentioned fix for concurrency does the trick for your application, but the problem is really not about changed hash in between?
I mean those two issue are really not related, however both of them may really lead to the mentioned `No 'Timer.Sample' registered for`.
I definitely can schedule release for tomorrow with this fix, but let's see first of all that there are no bugs to be fixed yet!
